export enum Configuration {
  ENV = 'NODE_ENV',
  PORT = 'PORT',
  CONNECT_DATABASE_DEV = 'CONNECT_DATABASE_DEV',
  CONNECT_DATABASE_TEST = 'CONNECT_DATABASE_TEST',
  CONNECT_DATABASE_PROD = 'CONNECT_DATABASE_PROD',
}
