export enum Configuration {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  CONNECT_DATABASE_DEV = 'CONNECT_DATABASE_DEV',
  CONNECT_DATABASE_TEST = 'CONNECT_DATABASE_TEST',
  CONNECT_DATABASE_PROD = 'CONNECT_DATABASE_PROD',
}
